# Generated by Django 4.1.7 on 2023-02-25 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActivityTracker',
            fields=[
                ('tracker_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('activity_date', models.DateField()),
                ('activity_count', models.IntegerField(blank=True, null=True)),
                ('act_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activitydata', to='activityapp.activity')),
            ],
            options={
                'db_table': 'activity_tracker',
                'managed': True,
            },
        ),
    ]
